version: '3'

services:
  aria2:
    build: .
    image: aria2:dev
    container_name: aria2_dev
    environment:
      - SECRET=yourtoken
      - UpdateTracker=true
      - QUIET=true
    volumes:
      - /d/docker/aria2/config:/config
      - /d/docker/aria2/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 6800:6800
    restart: unless-stopped