version: '3'

services:
  aria2:
    image: dobor/aria2
    container_name: aria2
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
      - SECRET=yourtoken
      - UpdateTracker=true
      - QUIET=true
    volumes:
      - /d/docker/aria2/config:/config
      - /d/docker/aria2/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 6800:6800
    restart: unless-stopped