#!/usr/bin/with-contenv sh

exec \
	s6-setuidgid aria2 aria2c \
    --conf-path=/config/aria2.conf \
    --rpc-secret=$SECRET \
    --disk-cache=$CACHE \
    --quiet=$QUIET \
    --check-certificate=false
  > /dev/stdout \
  2 > /dev/stderr